### ISSUE TITLE
How do i use aqua as api + user system

### ISSUE THREAD

**Issue by viraf** [jedireza/aqua#104]
When i try using the api endpoint for login. It always returns with error code 403 forbidden.

**Comment by jedireza** [comment]
Thanks for opening an issue.

We're using [`crumb`](https://github.com/hapijs/crumb), which helps diminish [csrf](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)) attacks. You'll get a new csrf token (via cookies) on each response from the server. The front-end code [looks for this token and passes it back](https://github.com/jedireza/aqua/blob/8d7ec24aedf9e52f756a61cccc70f3207dd59cba/client/helpers/json-fetch.js#L21-L23) to the server via the `X-CSRF-Token` header with each request made to the server.

This does make it harder to interact with the API manually, or via apps like Postman since you have to do that dance of finding the token from the cookie header and passing it token back via the `X-CSRF-Token` header with your next request.

Possible solutions:

 - You could disable `crumb` by [removing it from the `manifest.js` file](https://github.com/jedireza/aqua/blob/8d7ec24aedf9e52f756a61cccc70f3207dd59cba/manifest.js#L42-L49).
 - If you only want to disabled `csrf` protection during development you could modify `manifest.js` to only include crumb when `NODE_ENV=production`.
 - You can see if a different configuration would work better for you; see the [`crumb` docs](https://github.com/hapijs/crumb).

I hope this helps. If you find out you're still getting a 403s without `crumb`, by all means open a new issue. 👍

**Comment by jedireza** [comment]
I created a new wiki page for this too :shipit: 

https://github.com/jedireza/aqua/wiki/HTTP-403-forbidden-when-accessing-API-endpoints

**Comment by viraf** [comment]
I was going through the crumb docs and stumbled upon an issue in their repository. https://github.com/hapijs/crumb/issues/54

Does this require us to change the way we handle X-CSRF-Token for the api endpoints ?

Sorry, I am too much of a noob in the JS world to understand the impact of the issue.

**Comment by jedireza** [comment]
> I was going through the crumb docs and stumbled upon an issue in their repository. hapijs/crumb#54

I'm not sure if that issue is relevant here. It also sounds like they fixed whatever the issue was there.

> Does this require us to change the way we handle X-CSRF-Token for the api endpoints ?

If you want to interact with the api endpoints directly and not have to do the cookie/crumb dance, then yes. I noted some possible solutions.
