### ISSUE TITLE
Create Account Group from Non-Admin User

### ISSUE THREAD

**Issue by PsiOps** [jedireza/aqua#117]
Hi,

I'm looking into this framework for my app, and it looks pretty good! I was wondering if it's possible to have an non-admin user to create account groups? Is this a permission that I can grant a certain role? That would be awesome.

Thanks!

**Comment by jedireza** [comment]
Thanks for opening an issue.

> I'm looking into this framework for my app, and it looks pretty good!

Thanks. I like to refer to it as a boilerplate rather than a framework.

> I was wondering if it's possible to have an non-admin user to create account groups?

I don't see why not. You can create API endpoints and configure authorization however works best for your app.

> Is this a permission that I can grant a certain role?

Not exactly no. Accounts don't have a group feature by default. I suggest checking out the wiki:

 - [Admin & Admin Group Permissions](https://github.com/jedireza/aqua/wiki/Admin-%26-Admin-Group-Permissions)
 - [Users, Roles & Groups](https://github.com/jedireza/aqua/wiki/Users%2C-Roles-%26-Groups)
