### ISSUE TITLE
Passing SSL cert & key to the server instance

### ISSUE THREAD

**Issue by ajhool** [jedireza/aqua#139]
Hi, my goal is to simply serve Aqua at an https address, although I'm new to Hapi and am having trouble passing my tls creds to the server instance.

I have attempted to implement this by adding a tls field to the config.js/config object that contains my https cert and key, and accessing the field in the manifest, such that: manifest.js/manifest.connections.tls = Config.get('tls')

I have found a few Hapi solutions for TLS, but have not found anything that matches the config.js -> manifest.js -> server.js pattern, so I would appreciate any insight.

**Comment by jedireza** [comment]
Thanks for opening an issue. This is interesting because there can be multiple solutions.

My current preference is to put SSL/TLS termination in front of the application, which also makes it a bit easier to switch between production and dev environements. For example, using the Heroku SSL addon or with AWS using an elastic load balancer to terminate the SSL.

Otherwise you can use the `tls` option passed to [`server.connection`](http://hapijs.com/api#serverconnectionoptions).

> The `tls` object is passed unchanged as options to the node.js HTTPS server as described in the [node.js HTTPS documentation](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener). Set to `true` when passing a `listener` object that has been configured to use TLS directly.

If you're passing the key/cert combination, the `tls` object would look something like this:

```js
{
  key: fs.readFileSync('test/fixtures/keys/agent2-key.pem'),
  cert: fs.readFileSync('test/fixtures/keys/agent2-cert.pem')
}
```

Alternatively as the docs mention you could also create a https server yourself and pass it as the `listener` property of the connection.

**Comment by jedireza** [comment]
There was an [old issue in the `hapijs/glue`](https://github.com/hapijs/glue/issues/46) repo that sounds relevant.

**Comment by symbianm** [comment]
I used [hapi-require-https](https://www.npmjs.com/package/hapi-require-https) plugin to solve SSL issue with AWS load balancer. Just sharing experience.

**Comment by jedireza** [comment]
Thanks for sharing that @symbianm. That plugin does help with ensuring all requests use `https://`. I've also used static AWS s3 hosting to perform that redirect.

**Comment by ajhool** [comment]
Thanks @jedireza and @symbianm for the response and solutions. I think placing the ssl/tls termination in front of the application will be my preferred approach.
