### ISSUE TITLE
ldap as a backend

### ISSUE THREAD

**Issue by pierreozoux** [jedireza/aqua#149]
I'm looking into writing a web interface to manage ldap. Current options are not satisfying, so the plan is to develop one from scratch using probably nodejs.

(If you want to see more about the project, check: https://lab.allmende.io/ispcoop/souk/ )

I was searching to not reinvent the wheel, and I saw your nice project, it looks like what I'm looking for.

Would it be possible for me to write a module to make an ldap backend?
I guess your code is not really prepared to have modules, so it would need some preparatory work?

What are your thoughts on that?

Thanks!

**Comment by jedireza** [comment]
Thanks for opening an issue. The cool thing about [the way hapi does authentication strategies](https://hapijs.com/tutorials/auth?lang=en_US) is that you can write your own if one doesn't exist. Once you create that you'd just need to [change the configuration setting for the routes](https://github.com/jedireza/aqua/blob/ffec3a220ee36e7f7c8ec1dc105d06ee4823a1f8/server/api/users.js#L21) you want to use that strategy.

I did find this old demo code that claims to use ldap with hapi, maybe this would be a good starting point for you.

https://github.com/joyrexus/auth-demos/blob/87873aac36aed7e3aff7e95eb9a78acc1e297518/ldap-auth/index.js

I'm sure other customizations would need to be made since User/Account creation/registration would likely be different in the case of LDAP.

Please update this issue with your findings and/or solutions for future searchers. 🙏
