### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by ndaidong** [jedireza/aqua#159]
It should go with docker.

**Comment by jedireza** [comment]
Thanks for opening an issue.

Using docker may be a good solution for some, though I don't think it should be included by default. A couple things that come to mind about why it's not a good idea to include:

 - Since we require a running MongoDB instance, would we include a separate Docker image for that service too or assume it's ok to bundle it in the same container.
 - Adding Docker creates one more thing to maintain.

I would love to add a new [wiki guide](https://github.com/jedireza/aqua/wiki) for this though. Feel free to create it.
