### ISSUE TITLE
first-time-setup

### ISSUE THREAD

**Issue by rncortes1990** [jedireza/aqua#161]
How do you do the first-time-setup with the docker-compose, because de dokerized app, is not configured for this first setup.... I mean for the admin data, what can I do to achieve this?

**Comment by jedireza** [comment]
Thanks for opening an issue.

I don't use docker with Aqua myself. If I remember correctly @madnight provided the content for the wiki page. Hopefully they can help answer this question.

Please update the wiki with the solution when found. 🙏

**Comment by madnight** [comment]
For a automatic solution the command `npm run first-time-setup` should be idempotent to execute it as an https://docs.docker.com/compose/compose-file/#command composer command otherwise a entrypoint.sh would be necessary. However you can do it manually by joining into your running docker image and call the first-time-setup (that is what i did).
