### ISSUE TITLE
Keep a Store in Context when new User Input Form is opened

### ISSUE THREAD

**Issue by cshutchinson** [jedireza/aqua#21]
Thank you for all the work you have generously shared with the Github community. I have spent a great deal of time learning how aqua functions but have run into a roadblock and can't pass.

When the following code is executed in Actions.js, I lose the instance of store that was created by the page currently displayed. I need to pass data from this lost Store to the new page loaded in the code below. What is the best practice for saving store state and data between URL changes without using a Modal form?
```
Fetch(request, function (err, response) {

            if (!err) {
                window.location.href = '/account';
                response.success = true;
            }
```
My goal is simply to pass a username to the new displayed URL so I can implement that as a foreign key in a new mongdb collection created in the new URL.  I am reluctant to pass the data via a react-router param, but maybe that is the best approach? Can you comment? 

Thank you for your time.

**Comment by jedireza** [comment]
> Thank you for all the work you have generously shared with the Github community.

No thank you. :v: 

That snippet looks like its from the signup page actions:
https://github.com/jedireza/aqua/commit/ba0319272fe6510fd55744526e95a542d4ddbb1b#L26-L29

Although I don't think I fully understand your goal, you may be able to store the username in `localStorage` before the redirect fires and read it back out on the `/account` page.

Passing the data to `react-router` won't help here because the browser is actually changing pages.

I hope that helps.

**Comment by cshutchinson** [comment]
Thank you. I think I have it figured out.
