### ISSUE TITLE
What is the purpose of Statuses?

### ISSUE THREAD

**Issue by jacogreyling** [jedireza/aqua#227]
You have the concept of 'Statuses' and for the life of me I don't see the use for it? Can you perhaps explain? I'm tempted to remove that part of the code because the demo system I'm building. Also thinking of removing Accounts, as all I need is Users and Admins. Another idea will be to make it modular so that you can decide during install time which components you want to install. Just a thought.

**Comment by jedireza** [comment]
Here's an example. I went into the status manager and added a couple statuses. The pivot was `Account` for both of these so they end up showing up in the drop down in the account details screen.

<img width="1200" alt="screen shot 2017-08-04 at 8 06 23 pm" src="https://user-images.githubusercontent.com/979929/28992437-99bd260c-7950-11e7-9f0b-9fd1b49e72a3.png">

Then in the account details screen I'm able to select one and hit change.

<img width="1209" alt="screen shot 2017-08-04 at 8 08 25 pm" src="https://user-images.githubusercontent.com/979929/28992439-b7d83122-7950-11e7-8f49-d6bcca7e30d3.png">

The statuses can be anything you like. One cool thing is that we could add a filter to the account search screen and only see accounts that have certain current status.

Another cool thing is that a history is kept of who change the status and when. Here I've changed the status.

<img width="1194" alt="screen shot 2017-08-04 at 8 10 08 pm" src="https://user-images.githubusercontent.com/979929/28992443-f34eddc8-7950-11e7-926e-7dfda6a20268.png">

The reason why there is a pivot is because we can apply this exact same pattern to a new collection, like account orders for example and have order statuses.

I hope that helps answer your question. 👍
