### ISSUE TITLE
Production readiness vs. drywall 

### ISSUE THREAD

**Issue by facultymatt** [jedireza/aqua#38]
I've noticed that Aqua is missing a few features when compared to Drywall. I also know that Aqua has many more features in some ways since it leverages the Frame API, React, etc!!!

Notably missing: 
- Complete documentation
- Sitewide search
- Social signons

I'm excited to use this for production, but have a few questions: 
- How production ready would you consider Aqua vs. drywall? 
- What is the roadmap (if any) for porting over other features?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> I've noticed that Aqua is missing a few features when compared to Drywall. ... Complete documentation, Sitewide search, Social signons

This was done on purpose.

> How production ready would you consider Aqua vs. drywall?

I'd reach for Aqua before Drywall today. Especially because of the test coverage, as Drywall has none at this point. I'd say they're both just as dangerous as the next. :wink:

> What is the roadmap (if any) for porting over other features?

There is none. I'd be more interested in what we can take away.

**Comment by rstormsf** [comment]
Once I become comfortable with code in Aqua, I plan to use `bell` plugin for oauth social plugins sign up
