### ISSUE TITLE
How to make aqua isomorphic?

### ISSUE THREAD

**Issue by sheriffmohamed** [jedireza/aqua#39]
Aqua has been a huge help so far, thank you @jedireza for taking the time to put something like this together. :) 

I'm running into an issue trying to make the application isomorphic. Would you happen to have any words of wisdom or sample code that I can follow to get me over this hurdle?

**Comment by jedireza** [comment]
Thanks for opening an issue. I touched on this a while ago:

> I've purposefully stayed away from isomorphic design patterns. Isomorphic apps require a level of assumptions/opinions I didn't want to introduce. I've used Aqua as a learning experiment, to build a larger-sized app with a vanilla Flux implementation.

I wrote that when I was at Yahoo and working with the [Fluxible](http://fluxible.io/) team.

Also, I don't see an upside in making the admin CRUD screens isomorphic since they're behind authentication and not meant to be indexed by search engines. I'll continue with the assumption that we're not talking authenticated screens.

I've [done a talk on isomorphic apps](https://docs.google.com/presentation/d/1LdTKrxw0MdvH_VCkpWG2q5hS3pKvIA1IzbL3d3cZ1Ok/edit#slide=id.p) and how we brought Flux to the server with Fluxible. In that talk I demonstrate [the worlds smallest isomorphic React application](https://github.com/jedireza/mini-isomorphic-react), which gives us a glimpse at what the high level goal is to make a page built with React and Flux isomorphic.

##### Choosing an isomorphic Flux framework is a big decision that'll probably come with a little vendor lock-in.

Making your app isomorphic will touch your stack from top to bottom. Routing on the client and server need to line up. Flux on the server get's tricky because you can't use singletons and must isolate each request and you have to make actions asynchronous so you know when it's time to render the view. You'll also need to have a data access layer done in a way so that on the server it accesses resources directly but on the client those same calls are proxied via ajax requests (see [Fluxible's data services guide](http://fluxible.io/guides/data-services.html)).

Because there are so many considerations it's hard to recommend one over another. My advice is to study and compare the different approaches and choose what works best for your project.

- - - - - -

It may be helpful to review this repo: https://github.com/voronianski/flux-comparison

Relay and GraphQL could be promising for isomorphic apps in the future: http://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html
