### ISSUE TITLE
why not to have 1 react-router file with all routes defined in 1 place?

### ISSUE THREAD

**Issue by rstormsf** [jedireza/aqua#59]
just a question

**Comment by jedireza** [comment]
Thanks for opening an issue about this.

The reason why I chose not to is because it makes breaking the code up easier. For example, if I'm a random user just browsing the front-end site, I don't need all the admin/account/login code sent down and parsed since I won't use it. Same goes for if I'm just an account and not an admin, why would I need to load and parse all that admin code that I'd never use.

Great question.
