### ISSUE TITLE
Frame

### ISSUE THREAD

**Issue by moklick** [jedireza/aqua#64]
Hello,

I was wondering why you are not using your [frame](https://github.com/jedireza/frame) backend for aqua?

**Comment by jedireza** [comment]
Thanks for opening an issue.

We started Aqua using Frame, so essentially it bakes it in. There are some customizations madethat need to be made, like changing the auth strategy (`hapi-auth-basic` -> `hapi-auth-cookie`) and the login functionality in Aqua will check for a session and redirect unlike Frame. Because of this they projects can drift. Frame got updated a while back for hapi v9 and I've been waiting to upgrade Aqua for when React Router v1 ships.

**Comment by moklick** [comment]
:+1: thanks
