### ISSUE TITLE
Drywall / Aqua - Which one?

### ISSUE THREAD

**Issue by Ulydev** [jedireza/aqua#66]
Hello jedireza,
First of all, thanks a **lot** for developing Drywall and Aqua. This has saved me a lot of trouble, and although I've never used NodeJS, I'm progressively learning the technologies you use by looking at the source code. I could never thank you enough for the impressive work you've done.

I actually have a website based on Drywall, and I'd like to implement a few features I need some clarification on.

-I'd need to detect online presence in order to display a list of currently connected users. For now, I'm using a "heartbeat" Ajax function that sends a request to the server every 10 seconds. The server then updates the user MongoDB document and sets a "lastActive" value to the current date. It seems to barely work, but I'm really not sure if that's the proper way to do it. I must say I'm worried about performance when server is updating hundreds of Mongo documents every second.

Also, I didn't manage to display of all online users (for instance, those whose lastActive date has a 30 seconds delta with the current date). I've looked at the /admin/users/ code, but I just can't seem to understand how you'd do a Mongo query with filters and list every user that conforms to it.
I think it would be pretty important to add that the online presence should be able to handle about ~10 000 users at the same time.

-In the future, we'll be developing an iOS/Android mobile app for the website. As a mobile developer, these are going to be native applications. To you, what would be the easiest user system to work with? Drywall, or Aqua?

Thanks in advance for your help, and keep up the **awesome** work.
Ulysse

**Comment by jedireza** [comment]
Thanks for opening an issue.

> First of all, thanks a lot for developing Drywall and Aqua.

You're very welcome. It's always nice to hear.

> I'd need to detect online presence in order to display a list of currently connected users. [...]

I'd look into using [socket.io](http://socket.io) if you're using express. And [nes](https://github.com/hapijs/nes) if you're using hapi.

At first thought I'm not sure I'd try to attach this presence data to my MongoDB documents and try to query on them later. Because this data is (usually) temporal, I'd take a look at using something like Redis. Redis is really fast and takes the load of of MongoDB while still being query-able.

> In the future, we'll be developing an iOS/Android mobile app for the website. As a mobile developer, these are going to be native applications. To you, what would be the easiest user system to work with? Drywall, or Aqua?

YMMV but, I'd go a step further and start with [Frame](https://github.com/jedireza/frame/). Frame doesn't come with a front-end, so this gives you the opportunity of focusing on making your business logic API really solid while keeping assumptions related to the client (website, ios, android) totally separate.

Client side code can get stale very quickly these days. Aqua is in need of some upgrades. React `0.14` was released recently. I'm waiting for React Router `1.0` before starting to upgrade Aqua. Also I may take the opportunity to try making Aqua use [GraphQL](https://github.com/facebook/graphql) and use maybe even use [Redux](https://github.com/rackt/redux).
