### ISSUE TITLE
Navbar disappearing when resized to mobile

### ISSUE THREAD

**Issue by juanjocorzo** [jedireza/aqua#71]
The navbar disappears when resized to mobile-size. There's no toggle button to expand/collapse the menu.

**Comment by jedireza** [comment]
Thanks for opening an issue. Actually, the front-end of Aqua is pretty simple and mostly static. The hamburger icon isn't implemented since we're not using jQuery and hence not using the Bootstrap jQuery helpers.

The admin area does indeed have this functionality. But again, we're not using jQuery so that functionality had to be instrumented manually. You can see us doing that here: https://github.com/jedireza/aqua/blob/d24c057e8612ab939d0da3cc8e16f71346a1d91a/client/pages/admin/components/NavBar.jsx#L32-L35

![screenshot from 2015-12-02 21-59-47](https://cloud.githubusercontent.com/assets/979929/11553116/78b8e9ec-9940-11e5-8b82-95f2c854bc89.png)
