### ISSUE TITLE
Adding a resolve.alias to Webpack configuration

### ISSUE THREAD

**Issue by hybr1dz** [jedireza/aqua#75]
Hi, i'm trying to use https://github.com/dataminr/react-components in Aqua, and it requires adding a RequestHandler alias for the application, like this:

    resolve: {
        alias: {
            RequestHandler$: path.join(__dirname, 'path', 'to', 'request', 'library'),
        }
    },

I tried changing the webpack.js file in Aqua to look like this:

        resolve: {
        alias: {
            RequestHandler$: path.join(__dirname, 'RequestHandler.js'),
        },
            extensions: ['', '.js', '.jsx']
        },
But it still does not resolve. Am i modifying the right place correctly?

**Comment by jedireza** [comment]
Thanks for creating an issue. Since this isn't related to Aqua directly I'm not sure how much I'll be of help.

Base on this line from their docs:

> If using a component which requests data from your APIs, add a mapping to your webpack config for the component which will be responsible for making requests

[According to their example request handler](https://github.com/dataminr/react-components/blob/master/examples/RequestHandler.js#L203-L228) your module needs to be an object with a `request` property which is the function to call.

```js
{
  request: function (url, data, successCallback) {
    //do some async stuff and then call the successCallback with the results
  }
}
```

I hope this helps and much luck. :shipit:

**Comment by hybr1dz** [comment]
Yes i agree that it's a bit questionable whether this is related to Aqua. However it seems that the resolve.alias isn't working in general, so i was wondering if i was editing the right place since the application structure seems to be a bit different compared to the examples in react-components (no webpack.config.js for example).
