### ISSUE TITLE
core.min.js generating point

### ISSUE THREAD

**Issue by choy315** [jedireza/aqua#82]
i want to include bootstrap.js into core.min.js
where can i bind them to the new core.min.js file?

**Comment by jedireza** [comment]
Thanks for opening an issue. :+1:

We're using Gulp for the front-end build system. The Gulp files are located in `./gulp/`. For JS we're using using Webpack inside of our Gulp task. The file is [`./gulp/webpack.js`](https://github.com/jedireza/aqua/blob/d24c057e8612ab939d0da3cc8e16f71346a1d91a/gulp/webpack.js).

Re: [Bootstrap's JavaScript](http://getbootstrap.com/javascript/)

> Also note that all plugins depend on jQuery [...]

Since we're not using jQuery we need to reimplement the funtionality as React components. For example, to get [Bootstrap Modals](http://getbootstrap.com/javascript/#modals) to work, we implemented [`./client/components/Modal.jsx`](https://github.com/jedireza/aqua/blob/d24c057e8612ab939d0da3cc8e16f71346a1d91a/client/components/Modal.jsx).

Here is a Stackoverflow question that may help:
 - [Using JQuery plugins that transform the DOM in React Components?](http://stackoverflow.com/a/25514772)

I hope this helps.

**Comment by kylehq1** [comment]
Hello,
I see we have the modal.jsx in our components,
how do i wire it up inside the home/index.js so when i click a button the modal pops up?

Thank you.
