### ISSUE TITLE
Upgrading to Frame Unknown authentication strategy session in /login/{glob*}

### ISSUE THREAD

**Issue by hydrotik** [jedireza/aqua#85]
In the process of upgrading to Frame and seeing this issue:
```
Unknown authentication strategy session in /login/{glob*}
```

**Comment by hydrotik** [comment]
https://github.com/jedireza/aqua/issues/84

**Comment by jedireza** [comment]
In Frame, we're using `simple` strategy via a `basic` scheme, which is simple for an "API" only. This is defined here in Frame's [`/server/auth.js`](https://github.com/jedireza/frame/blob/ffab2edba6509028652090373bab28419d2351d6/server/auth.js#L15) file.

Aqua takes Frame and builds a more opinionated system including a front-end. Another opinion is to use `session` strategy via a `cookie` scheme, which makes it easier to create a more complete feeling system. This is defined here in Aqua's [`/server/auth.js`](https://github.com/jedireza/aqua/blob/d24c057e8612ab939d0da3cc8e16f71346a1d91a/server/auth.js#L11) file.

More details about authentication with hapi can be found here: http://hapijs.com/tutorials/auth

The error you're getting is because in the routes we define the authentication strategy differently in Frame than in Aqua.

In Frame we're using the [`simple` strategy](https://github.com/jedireza/frame/blob/ffab2edba6509028652090373bab28419d2351d6/server/api/accounts.js#L23-L26):

```js
            auth: {
                strategy: 'simple',
                scope: 'admin'
            },
```

And in Aqua we're using the [`session` strategy](https://github.com/jedireza/aqua/blob/d24c057e8612ab939d0da3cc8e16f71346a1d91a/server/api/accounts.js#L16-L19):

```js
            auth: {
                strategy: 'session',
                scope: 'admin'
            },
```

**Comment by hydrotik** [comment]
Thank you for the info as always!

**Comment by hydrotik** [comment]
Sorry one more question. Any idea why this might be coming up?
```
[3]    /server/api/login.js:114
[3]    request.auth.session.set(result);
[3]                                     ^
[3] 
[3] TypeError: Cannot read property 'set' of undefined
```
I'm going to do some digging, but I tried integrating the changes from the PR and it solved a number of issue, but this did pop up when going through the pages and trying to login. very likely could have to do with the way we are passing the data using redux which needs to be update to reflect the changes.

**Comment by jedireza** [comment]
> `TypeError: Cannot read property 'set' of undefined`

For some reason `requst.auth.session` isn't being set. Without being able to debug it's hard to tell.

**Comment by hydrotik** [comment]
when logging request.auth I get:
```
{ isAuthenticated: false,
credentials: null,
artifacts: null,
strategy: null,
mode: null,
error: null }
```
Working in the PR branch so I'll just keep digging away, but can't think of what is missing from the branch.

**Comment by jedireza** [comment]
I just checked out the `update-deps` branch out and logged in... and didn't get that error. I'm not sure whats different without seeing the code. I even deleted my `/node_modules` directory to be sure it wasn't an unexpected dependency change.

**Comment by hydrotik** [comment]
I was missing request.cookieAuth.set(result); in my code in case anyone comes across this
